### ISSUE TITLE
RED.util.evaluateJSONataExpression

### ISSUE THREAD

**Issue by GeorgeCastanza** [TLacke/node-red-multi-sensor#8]
I'm getting this error in Node Red

"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

Error
    at evaluateJSONataExpression (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at Object.evaluateNodeProperty (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:673:18)
    at getData (/root/.node-red/node_modules/node-red-contrib-multi-sensor/**multiSensor**.js:271:38)
    at Object.onDeactivate (/root/.node-red/node_modules/node-red-contrib-multi-sensor/**multiSensor**.js:137:29)
    at Object.deactivate (/root/.node-red/node_modules/node-red-contrib-multi-sensor/**multiSensor**.js:127:26)
    at Object.deactivate (/root/.node-red/node_modules/node-red-contrib-multi-sensor/**multiSensor**.js:209:30)
    at Object.timeOut (/root/.node-red/node_modules/node-red-contrib-multi-sensor/**multiSensor**.js:226:30)
    at Timeout.<anonymous> (/root/.node-red/node_modules/node-red-contrib-multi-sensor/**multiSensor**.js:220:61)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

I bolded MultiSensor.

**Comment by TLacke** [comment]
Oh, I'll take a look at it.
Thanks for letting me know!
